# Workflow name
name: action-workflow

# Triggers for the workflow
on:

  # Automatic trigger on push events to the master branch
  push:
    branches:
      - main

# Jobs defined in the workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    steps: 
      - name: Run custom action
        uses: ulaga1/githubactions@main

        